# Insert chapter 2 title here

*Describe the work you have done this week and summarize your learning.*

- Describe your work and results clearly. 
- Assume the reader has an introductory course level understanding of writing and reading R code as well as statistical methods
- Assume the reader has no previous knowledge of your data or the more advanced methods you are using  

#introducing the data

learning2014 <- read.csv("learning2014.csv")

learning2014
str(learning2014)
dim(learning2014)

#graphical overview

pairs(learning2014[-1], col = learning2014$gender)

#introducing two packages...

library(ggplot2)
library(GGally)

#...to provide an overview

p <- ggpairs(learning2014, mapping = aes(col = gender, alpha = 0.3), lower = list(combo = wrap("facethist", bins = 20)))

p

#a summary of variables

points <- lm(Points ~ Attitude, data = learning2014)

points <- lm(Points ~ stra, data = learning2014)

points <- lm(Points ~ Age, data = learning2014)

points <- lm(Points ~ deep, data = learning2014)

points <- lm(Points ~ surf, data = learning2014)

#some plots

qplot(Attitude, Points, data = learning2014) + geom_smooth(method = "lm")

#model

pointsmodel <- lm(Points ~ stra, data = learning2014)


#model validation

par(mfrow = c(2,2))
plot(pointsmodel,which = c(1, 2, 5))


